project:
  type: website
  output-dir: docs  # Output directory set to docs  

website:
  title: "Introduction to Data Analysis with R and Bioconductor"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Introduction to R"
        href: 1.bioc_intro_Introduction2R_solutions.qmd 
      - text: "Intro to R (suite)"
        href: 2.bioc_intro_Intro2R_2_solutions.qmd
      - text: "Data Manipulation with dplyr"
        href: 3.bioc_intro_DataManipulation_solutions.qmd
      - text: "Data Visualization with ggplot2"
        href: 4.bioc_intro_DataVisualization_solutions.qmd
format:
  html:
    toc: true  # Enables table of contents for each page
    theme: cosmo  # You can use other themes like flatly, cerulean, etc.
